0.966  2022/03/20  SNOOPYJC  Fixes for issues s3, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, and others
Don't message about translating a std lib file if we already have it translated,
give warning on ref of ,
don't die on empty input file,
issue s7 - complex expression with || messes up the nesting level,
issue s9 - return list needs to return Array([list]),
issue s10 - variables declared my/local/state with no init are initialized twice,
add File::Spec file_name_is_absolute, catfile, rel2abs, abs2rel,
issue s8 - int values passed to regex, s, or tr weren't being convered to strings,
issue s11 - * bare_word being treated as typeglob,
issue s12 - return from BEGIN block generating wrong code,
issue s13 -  = eval '...' wasn't handled and line with only 0 wasn't being tokenized and nested eval wasn't returning a result,
addl fix to remove extra * on issue 37,
issue s3 - add functions ceil, floor, trunc, round, exp, log, sin, cos - change exp(99999) to math.inf and also 9**9**9,
handle open with single argument,
issue s14 - 0Package::var doesn't work,
issue bootstrap - substitution in a function arg generates bad code,
bare word followed by a scalar or constant is not a string - it's a sub ref,
handle multiple ''' on a line in eat_strings - symptom - import line wasn't being cleaned up in test_complex.py,
issue bootstrap - generate the right exception name for plain next or last used in a labeled loop,
issue s3 - fix syntax error from functions in complex ? : expression,
remove extra parens from sprintf and defined functions,
add 're' to the list of names that need to be escaped,
add '.pattern' to a compiled regex variable used in another regex,
if user imports a package that includes a predefined function - call that instead of ours,
generate proper code for [0],
ignore the o flag on a regex,
import exp, cos, and sin from a package if they are overloaded even if they are not in @EXPORT,
add and use _flt() for conversions to float - like for math functions,
properly splat the arguments even if the sub call is fully qualified,
list of strings with an int at the end was being incorrectly typed as 'a of S',
implement 'wantarray',
issue s15 - handle 'a'.1234 as concat,
issue s16 - named capture groups are not properly translated into python,
implement select function, defined(&POSIX::_exit) was calling the function,
implement kill via perllib.kill,
assigning to a hashref or arrayref scalar from a {...} or [...] wasn't making the value a Hash or Array,
generate proper code for substr with incr/decr included

diff --git a/tests/boot b/tests/boot
--- a/tests/boot
+++ b/tests/boot
@@ -3,7 +3,20 @@
 export PYTHONPATH=/c/pythonizer/pythonizer
 echo "Boottrapping pythonizer"
 cd ../../bootstrap
-./run
+# Copy over the library files, as defined in bump.yaml
+grep '\.py:' ../pythonizer/bump.yaml | while read -r line; do
+    dir=$(dirname $line)
+    case "$dir" in
+    .) ;;
+    *) echo cp -r ../$dir ../../bootstrap
+       cp -r ../pythonizer/$dir .;;
+    esac
+done
+./run -v2
+if [ $? -ne 0 ]; then
+    echo "Bootstrap failed!"
+    exit 1
+fi
 cd ../pythonizer/tests
 
 echo "Building perllib"
@@ -69,7 +82,7 @@ if [ "$mflag" != "-m" ]; then
 	   break
 	fi
         echo "==================== $f ====================" >run1.log
-        pypy ../../bootstrap/main.py -v0 $flags $f >>run1.log 2>&1
+        pypy -OOO ../../bootstrap/main.py -v0 $flags $f >>run1.log 2>&1
         if [ $? -ne 0 ]; then
            echo "$f run with pythonizer FAILED" >>run1.log
            ((failed++))
@@ -154,7 +167,7 @@ do
    fi
    # Make sure it says "test passed" twice
    count=`grep -c "test passed" run1.log`
-   if [ $count -ne 2 ]; then
+   if [[ $count -ne 2 && "$f" != "issue_empty_file.pl" ]]; then
       echo "test $f failed because 2 'test passed' messages were not found!" >>run1.log
       ((failed++))
       status=1
