1.012  2022/11/07  SNOOPYJC Fixes for issues s140, s141, s142, s143, s144, s145, s146, s147, s148, s149, s150
issue s140:  doesn't work,
issue s141: Naming a sub 'main' fails to pythonize properly,
issue s142: Autovivification doesn't work on @ARGV, also fix range assignment for @ARGV,
issue s143: Complex hash assignment with regex substitute generates incorrect code,
issue s144: my statement with a comma-separated list of initializations generates bad code,
issue s145: complex nested hash/array initialization fails translation,
issue s146: for loop that starts by incrementing the loop counter is not handled,
issue s147: multiple do{...} until(...) with nested trailing 'if' does not translate properly,
issue s148: chomp/chop on an array element or hash value fails to translate,
issue s149: multi-line q string with blank lines doesn't translate properly,
issue s150: GetOptions or die generates bad code, other fixes to GetOptions to handle -option and check for invalid options

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -138,7 +138,7 @@ done;
 
 echo
 echo "Running pythonizer tests"
-for f in *.pl;
+for f in *.pl *.pln;
 do
    if [ $ctrlc -eq 1 ]; then
       break
@@ -157,16 +157,19 @@ do
    fi
    echo "==================== $f ====================" >run1.log
    ((tests++))
-   perl $f >>run1.log 2>&1
-   if [ $? -ne 0 ]; then
-      echo "$f run with perl FAILED - skipping next steps" >>run1.log
-      ((failed++))
-      status=1
-      red E
-      cat run1.log >>run.log
-      rm -f run1.log
-      continue
-   fi
+   case "$f" in
+   *.pln) echo "$f - test passed" >>run1.log;;
+   *) perl $f >>run1.log 2>&1
+      if [ $? -ne 0 ]; then
+         echo "$f run with perl FAILED - skipping next steps" >>run1.log
+         ((failed++))
+         status=1
+         red E
+         cat run1.log >>run.log
+         rm -f run1.log
+         continue
+      fi;;
+   esac
    error_test=0
    case "$f" in
    error*) error_test=1;;
@@ -198,7 +201,10 @@ do
            continue
        fi
    fi
-   pyf=${f%.pl}.py
+   case "$f" in
+   *.pln) pyf=${f%.pln}.py;;
+   *.pl)  pyf=${f%.pl}.py;;
+   esac
    python $pyf >>run1.log 2>&1
    if [ $? -ne 0 ]; then
       echo "$pyf run with python FAILED" >>run1.log
