1.012  2022/11/07  SNOOPYJC issue s140:  doesn't work, issue s141: Naming a sub 'main' fails to pythonize properly, issue s142: Autovivification doesn't work on @ARGV, also fix range assignment for @ARGV, issue s143: Complex hash assignment with regex substitute generates incorrect code, issue s144: my statement with a comma-separated list of initializations generates bad code, issue s145: complex nested hash/array initialization fails translation, issue s146: for loop that starts by incrementing the loop counter is not handled, issue s147: multiple do{...} until(...) with nested trailing 'if' does not translate properly, issue s148: chomp/chop on an array element or hash value fails to translate, issue s149: multi-line q string with blank lines doesn't translate properly, issue s150: GetOptions or die generates bad code, other fixes to GetOptions to handle -option and check for invalid options

diff --git a/tests/runit b/tests/runit
--- a/tests/runit
+++ b/tests/runit
@@ -18,16 +18,30 @@ do
    -*) flags="$flags $f"
        continue;;
    esac
-   f=${f}.pl
+   pyopt=
+   if [ -e ${f}.pl ]; then
+       f=${f}.pl
+       pyf=${f%.pl}.py
+   elif [ -e ${f}.pm ]; then
+       f=${f}.pm
+       pyf=${f%.pm}.py
+       pyopt=-m py_compile
+   else
+       f=${f}.pln
+       pyf=${f%.pln}.py
+   fi
    echo "==================== $f ===================="
    ((tests++))
-   perl $f
-   if [ $? -ne 0 ]; then
-      echo "$f run with perl FAILED - skipping next steps"
-      ((failed++))
-      status=1
-      continue
-   fi
+   case "$f" in
+   *.pln)   echo "Skip run with perl for $f";;
+   *) perl $f
+      if [ $? -ne 0 ]; then
+         echo "$f run with perl FAILED - skipping next steps"
+         ((failed++))
+         status=1
+         continue
+      fi;;
+   esac
    ${prefix}../pythonizer -v0 $flags $f
    if [ $? -ne 0 ]; then
       echo "$f run with pythonizer FAILED"
@@ -35,8 +49,7 @@ do
       status=1
       continue
    fi
-   pyf=${f%.pl}.py
-   python $pyf
+   python $pyopt $pyf
    if [ $? -ne 0 ]; then
       echo "$pyf run with python FAILED"
       ((failed++))
